config/routes.rb
Rsvpct::Application.routes.draw do

  resources :groups do 
	resources :timeslots do
		resources :answers
	end
	resources :memberships
  end
  
  resources :players

  
  resources :sessions do
	collection do
		get :create_oauth
	end
  end
  

  root :to => 'groups#index'

end

app/models/membership.rb
class Membership < ActiveRecord::Base
	belongs_to :player
	belongs_to :group
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
	def index
		#current_group.memberships.each{ |d| d.delete }
		@members = current_group.members
		@owner = current_group.owner
	end
	
	def new
		@membership = Membership.new
	end
	
	def create
		@membership = Membership.new(params[:membership])
		@membership.player = Player.find(params[:player_id])
		@membership.group = current_group
		respond_to do |format|
		  if @membership.save
			format.html { redirect_to(group_memberships_url(current_group), :notice => 'membership was successfully created.') }
			format.xml  { render :xml => @membership, :status => :created, :location => @membership }
		  else
			format.html { render :action => "new" }
			format.xml  { render :xml => @membership.errors, :status => :unprocessable_entity }
		  end
		end
	end
end

app/helpers/memberships_helper.rb
module MembershipsHelper

	def available_players
		 @players = Player.all
		 @players.delete current_group.owner
		 current_group.players.each{ |p| @players.delete p }
		 @players
	end
end

app/views/memberships/_form.html.erb
<%= form_for([current_group, @membership]) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player %><br />
    <%= select_tag "player_id", options_for_select( available_players.map{|u| [u.name, u.id]} ) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memberships/index.html.erb
	<div data-role="header" data-position="fixed">
		<h1><%= current_group.name %></h1>
	</div>
	
	<div data-role="content">
		<ul data-role="listview">
			<li>
				<img src="http://www.gravatar.com/avatar/<%= md5 @owner.email %>?d=identicon&s=80"/>
				<h3><a><%= @owner.name %></a></h3>
				<span>Admin</span>
			</li>
			<% @members.each do |member| %>
				<li>
					<img src="http://www.gravatar.com/avatar/<%= md5 member.email %>?d=identicon&s=80"/>
					<h3><a><%= member.name %></a></h3>
				</li>
			<% end %>
		</ul>
	</div>

	<div data-role="footer" data-position="fixed">
		<div data-role="navbar">
			<ul>
				<li><a href="<%= new_group_membership_path(current_group) %>">Legg til spiller</a></li>
			</ul>
		</div>
	</div>

app/views/memberships/new.html.erb
	<div data-role="header" data-position="fixed">
		<h1>Ny spiller</h1>
	</div>
	<div data-role="content">
		<%= render 'form' %>
	</div>