config/routes.rb
Rsvpct::Application.routes.draw do

  resources :groups do 
	resources :timeslots do
		resources :answers
	end
	resources :memberships
  end
  
  resources :players

  
  resources :sessions do
	collection do
		get :create_oauth
	end
  end
  

  root :to => 'groups#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :player
  belongs_to :timeslot
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index
	@timeslot = Timeslot.find(params[:timeslot_id])
  end
  
  def show
	@timeslot = Timeslot.find(params[:timeslot_id])
  end

  def new
	@timeslot = Timeslot.find(params[:timeslot_id])
	@answer = @timeslot.answers.detect{|a| a.player == @user}
	if @answer == NIL
		
		@answer = Answer.new
		@answer.player = @user
		respond_to do |format|
		  format.html # new.html.erb
		  format.xml  { render :xml => @answer }
		end
	else	
		redirect_to url_for(:action => "edit", :id => @answer.id)
	end

  end

  def edit
	@timeslot = Timeslot.find(params[:timeslot_id])
	@answer = @timeslot.answers.detect{|a| a.player == @user}
  end


  def create
	@timeslot = Timeslot.find(params[:timeslot_id])
    @answer = @timeslot.answers.detect{|a| a.player == @user} || Answer.new(params[:answer])
	@answer.timeslot = @timeslot
	@answer.player = @user
    respond_to do |format|
      if @answer.save
		  format.html { render :action => "show" }
		  format.xml  { head :ok }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @answer.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @timeslot = Timeslot.find(params[:timeslot_id])
	@answer = Answer.find(params[:id]);
    respond_to do |format|
      if @answer.update_attributes(params[:answer])		
		format.html { render :action => "show" }
		format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @answer.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
	
	<div data-role="header" class="answerHeader">
		<h1><%= @timeslot.date %></h1>
	</div>
	<div data-role="content">
		<%= form_for([current_group, @timeslot, @answer], :remote => true, :html => {"data-ajax" => "false"}) do |f| %>
				<div data-role="fieldcontain">
					<input type="submit" data-icon="check" data-theme="b" value="Ja">
					<input type="hidden" name="answer[joining]" value="true">
					<label for="answer_extra">Tar med:</label>
					<%= select( "answer", "extra", { "Ingen" => 0, "1" => 1, "2" => 2, "3" => 3, "4" => 4, "5" => 5}, {}, { "data-native" => "true" }) %>

				</div>
		<% end %>
		<%= form_for([current_group, @timeslot, @answer], :remote => true) do |f| %>
				<div data-role="fieldcontain">
					<input type="submit" data-icon="delete" data-theme="e" value="Nei">
					<input type="hidden" name="answer[joining]" value="false">
					<input type="hidden" name="answer[extra]" value="0">
					<label for="answer_comment">Kommentar:</label><%= f.text_field :comment %>
				</div>
		<% end %>
	</div>

<script>
$(function() {
	$('form.edit_answer, form.new_answer').bind("ajax:complete", function() {
		$.mobile.changePage({url: '<%= group_timeslot_answers_url(current_group, @timeslot) %>'}, 'none', false, false)
	});
});
</script>

app/views/answers/edit.html.erb
<%= render 'form' %>

app/views/answers/index.html.erb
	<div data-role="header">
		<h1><%= dateFormat @timeslot.date %></h1>
	</div>

	<div data-role="content">
		<ul data-role="listview" class="playerList">


			<li data-role="list-divider">Kommer<span class="ui-li-count"><%= @timeslot.coming_count %></span></li>
			<% @timeslot.coming().each { |a| %>
				<li>
					<img src="http://www.gravatar.com/avatar/<%= md5 a.player.email %>?d=identicon&s=80"/>
					<h3><a><%= a.player.name %></a></h3>
					<% if (a.extra > 0) %>
						<span class="ui-li-count">+<%= a.extra %></span>
					<% end %>
				</li>
			<% } %>
			
			<li data-role="list-divider">Kommer ikke<span class="ui-li-count"><%= @timeslot.not_coming.count %></span></li>
			<% @timeslot.not_coming().each do |answer| %>
				<li>
					<img src="http://www.gravatar.com/avatar/<%= md5 answer.player.email %>?d=identicon&s=80"/>
					<h3><a><%= answer.player.name %></a></h3>
					<p><%= answer.comment %></p>
				</li>
			<% end %>

			<li data-role="list-divider">Mangler svar<span class="ui-li-count"><%= @timeslot.no_answer.count %></span></li>
			<% @timeslot.no_answer().each do |player| %>
				<li>
					<img src="http://www.gravatar.com/avatar/<%= md5 player.email %>?d=identicon&s=80"/>
					<h3><a><%= player.name %></a></h3>
				</li>
			<% end %>
		</ul>
	</div>
	<div data-role="footer" data-position="fixed">
	  <div data-role="navbar">
		<ul>
			<li><a href="javascript:$.mobile.changePage ({url: '<%= url_for(:controller => "timeslot", :timeslot_id => @timeslot.id, :controller => "answers", :action => "new") %>'}, 'slide', false, false)" data-icon="gear">Svar</a></li>
			<li><a href="javascript:$.mobile.changePage ({url: '<%= group_timeslots_url(params[:group_id], @timeslot) %>'}, 'none', false, false)" data-icon="refresh">Refresh</a></li>
		</ul>
	  </div>
	</div>

app/views/answers/new.html.erb
<%= render 'form' %>