config/routes.rb
Rsvpct::Application.routes.draw do

  resources :groups do 
	resources :timeslots do
		resources :answers
	end
	resources :memberships
  end
  
  resources :players

  
  resources :sessions do
	collection do
		get :create_oauth
	end
  end
  

  root :to => 'groups#index'

end

app/models/timeslot.rb
class Timeslot < ActiveRecord::Base
	has_many :answers
	belongs_to :group

	def coming
		answers.select { |a| a.joining }
	end
	
	def coming_count 
		coming().map{|a| a.extra + 1 }.reduce(0) { |sum, value | sum + value } 
	end

	def not_coming
		answers.select { |a| !a.joining }
	end
	
	def no_answer
		players = Player.find(:all)
		players.select { |p| answers.detect { |a| a.player == p } == NIL }
	end
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController

  def index
	@group = current_group
    @timeslots = @group.timeslots
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @timeslots }
    end
  end


  def show
    @timeslot = Timeslot.find(params[:id])
	redirect_to(group_timeslot_answers_path(current_group, @timeslot))
  end


  def new
    @timeslot = Timeslot.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @timeslot }
    end
  end


  def edit
    @timeslot = Timeslot.find(params[:id])
  end


  def create
    @timeslot = Timeslot.new(params[:timeslot])
	@timeslot.group = current_group
    respond_to do |format|
      if @timeslot.save
        format.html { redirect_to([current_group, @timeslot], :notice => 'Timeslot was successfully created.') }
        format.xml  { render :xml => @timeslot, :status => :created, :location => @timeslot }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @timeslot.errors, :status => :unprocessable_entity }
      end
    end
  end


  def update
    @timeslot = Timeslot.find(params[:id])

    respond_to do |format|
      if @timeslot.update_attributes(params[:timeslot])
        format.html { redirect_to([current_group, @timeslot], :notice => 'Timeslot was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @timeslot.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @timeslot = Timeslot.find(params[:id])
    @timeslot.destroy

    respond_to do |format|
      format.html { redirect_to(timeslots_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper

end

app/views/timeslots/_form.html.erb
<%= form_for([current_group, @timeslot]) do |f| %>
  <% if @timeslot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timeslot.errors.count, "error") %> prohibited this timeslot from being saved:</h2>

      <ul>
      <% @timeslot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.datetime_select :date, {:minute_step => 15, :start_hour => 16 } %>
  </div>
  <div class="actions">
    <%= f.submit "Lagre" %>
  </div>
<% end %>

app/views/timeslots/edit.html.erb
<h1>Editing timeslot</h1>

<%= render 'form' %>

<%= link_to 'Show', @timeslot %> |
<%= link_to 'Back', group_timeslots_path %>

app/views/timeslots/index.html.erb
	<div data-role="header" data-position="fixed">
		<h1><%= @group.name %></h1>
	</div>
	<div data-role="content">
		<ul data-role="listview">
			<% @timeslots.each do |timeslot| %>
			  <li>
				<h3>
					<%= link_to dateFormat(timeslot.date), group_timeslot_answers_path(@group, timeslot)  %>				
				</h3>
				<% if (timeslot.coming_count() > 0) %>
						<span class="ui-li-count"><%= timeslot.coming_count %></span>
				<% end %>
			  </li>
			<% end %>
		</ul>
	</div>

        <div data-role="footer" data-position="fixed">
          <div data-role="navbar">
                <ul>
                        <li><a href="<%= new_group_timeslot_path(@group) %>" data-icon="plus">Ny trening</a></li>
                        <li><a href="<%= group_memberships_path(@group) %>" data-icon="grid">Spillere</a></li>
						<li><a href="javascript:$.mobile.changePage ({url: '<%= group_path(@group) %>'}, 'none', false, false)" data-icon="refresh">Refresh</a></li>
                </ul>
          </div>
		  
        </div>

app/views/timeslots/new.html.erb
	<div data-role="header" data-position="fixed">
		<h1>Ny trening</h1>
	</div>
	<div data-role="content">
		<%= render 'form' %>
	</div>